=== mmerbes/G2PlanetCodeTest/Device Weight Summary/example.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://main.g2planet.com/codetest/example"
            xmlns:f="http://main.g2planet.com/codetest/example"
            xmlns:html="http://www.w3.org/1999/xhtml"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

  <xsd:complexType name="deviceElementType" id="deviceElementType">
    <xsd:complexContent>
      <xsd:extension base="f:openAttrs">
        <xsd:sequence>
          <xsd:element ref="f:weight" minOccurs="0" maxOccurs="1"/>
          <xsd:any namespace="##other" processContents="lax" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="quantity" type="xsd:positiveInteger" use="optional" default="1"/>
        <xsd:attribute name="serial_number" type="xsd:string" use="required"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="openAttrs" id="openAttrs">
    <xsd:complexContent>
      <xsd:restriction base="xsd:anyType">
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
      </xsd:restriction>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="positiveDecimalType" id="positiveDecimalType">
    <xsd:restriction base="xsd:decimal">
      <xsd:minExclusive value="0" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="weightElementType" id="weightElementType">
    <xsd:simpleContent>
      <xsd:extension base="f:positiveDecimalType">
        <xsd:attribute name="units" type="f:weightUnitType" use="optional" default="pounds" />
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="weightUnitType" id="weightUnitType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ounces" />
      <xsd:enumeration value="pounds" />
    </xsd:restriction>
  </xsd:simpleType>

  <!-- Element declarations -->
  <xsd:element name="device" id="device" type="f:deviceElementType"/>

  <xsd:element name="device-list" id="device-list">
    <xsd:complexType>
      <xsd:complexContent>
        <xsd:extension base="f:openAttrs">
          <xsd:sequence>
            <xsd:element ref="f:device" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:any namespace="##other" processContents="lax" minOccurs="0"/>
          </xsd:sequence>
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="weight" id="weight" type="f:weightElementType"/>
</xsd:schema>

=== mmerbes/G2PlanetCodeTest/Device Weight Summary/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<f:device-list xmlns:f="http://main.g2planet.com/codetest/example" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://main.g2planet.com/codetest/example.xsd">
  <f:device name="Voltage Converter" quantity="2" serial_number="20011">
    <f:weight units="pounds">3.00</f:weight>
  </f:device>
  <f:device name="24-port switch" quantity="2" serial_number="24PORTSW-004">
    <f:weight units="pounds">3.34</f:weight>
  </f:device>
  <f:device name="4GJetPack" quantity="4" serial_number="321422551487">
    <f:weight units="pounds">0.50</f:weight>
  </f:device>
  <f:device name="Metrologic Focus FirstFlash USB Barcode Gun Holder" quantity="1" serial_number="BRCDHLDR-10001">
    <f:weight units="pounds">3.00</f:weight>
  </f:device>
  <f:device name="Barcode Scanner" quantity="2" serial_number="BARCDSCNR-10011">
    <f:weight units="pounds">1.33</f:weight>
  </f:device>
  <f:device name="Brother printer" quantity="1" serial_number="BrthPrntr-01">
    <f:weight units="pounds">10.00</f:weight>
  </f:device>
  <f:device name="Cisco Aironet" quantity="1" serial_number="FHK0745J36K">
    <f:weight units="pounds">1.81</f:weight>
  </f:device>
  <f:device name="CP-60 Printer" quantity="8" serial_number="CP60-Printer">
    <f:weight units="pounds">6.00</f:weight>
  </f:device>
  <f:device name="Canon-EOS40D" quantity="1" serial_number="Canon-EOS40D-10001">
    <f:weight units="pounds">10.00</f:weight>
  </f:device>
  <f:device name="Jigsaw" quantity="24" serial_number="600040228">
    <f:weight units="pounds">1.53</f:weight>
  </f:device>
  <f:device name="Jigsaw Power" quantity="24" serial_number="JIGPWR-10081">
    <f:weight units="pounds">1.25</f:weight>
  </f:device>
  <f:device name="RW-400" quantity="18" serial_number="RW400-10008">
    <f:weight units="ounces">12</f:weight>
  </f:device>
  <f:device name="RW/400 PWR" quantity="18" serial_number="rw4pwr-10136">
    <f:weight units="pounds">0.63</f:weight>
  </f:device>
  <f:device name="Google Nexus-(SPH-D720)" quantity="80" serial_number="30349503C55F00EC">
    <f:weight units="pounds">1.00</f:weight>
  </f:device>
  <f:device name="Power transformer" quantity="5" serial_number="PWRTRNSFRMR-20001">
    <f:weight units="pounds">40.00</f:weight>
  </f:device>
  <f:device name="USB MagStripe Reader" quantity="1" serial_number="2TE1020291">
    <f:weight units="pounds">0.25</f:weight>
  </f:device>
  <f:device name="WebDT Reader" quantity="10" serial_number="430C01401943007">
    <f:weight units="pounds">0.94</f:weight>
  </f:device>
  <f:device name="iPad2" quantity="3" serial_number="SDLXGVVSXDFHW">
    <f:weight units="ounces">12</f:weight>
  </f:device>
</f:device-list>
